name: muyunspring-app

services:
  postgres:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: muyun_dev
      POSTGRES_DB: muyun_spring_app
    ports:
      - "54322:5432"
    volumes:
      - muyun-spring-app-postgres:/var/lib/postgresql

volumes:
  muyun-spring-app-postgres:
